spring.application.name=bitcoin-mcp-server
spring.ai.mcp.server.name=bitcoin-mcp-server
spring.ai.mcp.server.version=0.0.1

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
